name: Build Windows executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Configure Poetry cache
        run: |
          echo "POETRY_CACHE_DIR=${{ runner.temp }}\\poetry-cache" >> $Env:GITHUB_ENV

      # Use the committed lockfile; do not mutate it in build
      - name: Validate lock (no changes)
        shell: bash
        run: |
          poetry check --lock --no-interaction

      - name: Install dependencies
        shell: bash
        run: |
          poetry install --with dev --no-interaction --no-root

      - name: Download Parakeet assets
        shell: bash
        run: |
          poetry run python -c "from huggingface_hub import hf_hub_download; repo_id='istupakov/parakeet-tdt-0.6b-v2-onnx'; [hf_hub_download(repo_id=repo_id, filename=name, local_dir='.', local_dir_use_symlinks=False) for name in ['encoder-model.onnx','decoder_joint-model.onnx','vocab.txt']]"

      - name: Build executable with PyInstaller
        shell: bash
        run: |
          poetry run pyinstaller --log-level=DEBUG Parrator.spec

      - name: List build contents
        run: |
          dir dist
          dir dist\Parrator

      - name: Package release archive
        run: |
          Compress-Archive -Path dist/Parrator/* -DestinationPath Parrator-windows.zip -Force

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Parrator-windows-build
          path: |
            dist/Parrator
            Parrator-windows.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            Parrator-windows.zip
